---
- hosts: all
  become: yes
  remote_user: ansible
  tasks:
    - name: Update apt repo and cache on all debain/ubuntu
      apt: 
        update_cache: true 
        force_apt_get: true 
        cache_valid_time: 86400
    
    - name: upgrade all packages on servers
      apt: 
        upgrade: dist 
        force_apt_get: true
    
    - name: Check if a reboot is needed
      stat: 
        path: /var/run/reboot-required 
        get_md5: no
      register: reboot_required_file

    - name: Auto remove unneeded packages
      apt:
        autoremove: true

    - name: Reboot machines
      reboot:
        msg: "Reboot initiated by ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: up_time
      when: reboot_required_file.stat.exists
